name: "Auto-Index Obsidian Updater"
description: "A GitHub Action to automatically update Obsidian based on new files"
author: "d-a-v-e"
inputs:
  OPENAI_API_KEY:
    description: "OpenAI API key for generating content."
    required: true
  MY_GITHUB_TOKEN:
    description: "GitHub token for accessing the repository."
    required: true
outputs:
  success:
    description: "Indicates if the Index was successfully updated."
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.3"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run README Update Script
      run: python main.py
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
