name: "Auto-Index Obsidian Updater"
description: "A GitHub Action to automatically update Obsidian based on new files."
author: "d-a-v-e"
inputs:
  OPENAI_API_KEY:
    description: "OpenAI API key for generating content."
    required: true
  GH_TOKEN:
    description: "GitHub token for accessing the repository."
    required: true
  REPO_PATH:
    description: "The repository path in 'owner/repo' format."
    required: true
  PR_NUMBER:
    description: "The pull request number."
    required: true
outputs:
  success:
    description: "Indicates if the Index was successfully updated."
runs:
  using: "composite"
  steps:
    - name: Enable Debug Logging
      run: |
        echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      shell: bash

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.3"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run Index Update Script
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        REPO_PATH: ${{ inputs.REPO_PATH }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
      run: python main.py
      shell: bash