name: "Auto-Index Obsidian Updater"
description: "A GitHub Action to automatically update Obsidian based on new files."
author: "d-a-v-e"

inputs:
  OPENAI_API_KEY:
    description: "OpenAI API key for generating content."
    required: true
  GH_TOKEN:
    description: "GitHub token for accessing the repository."
    required: true
  REPO_PATH:
    description: "The repository path in 'owner/repo' format."
    required: true
  PR_NUMBER:
    description: "The pull request number."
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

  # Optionally, pass inputs as environment variables
  env:
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    GH_TOKEN: ${{ inputs.GH_TOKEN }}
    REPO_PATH: ${{ inputs.REPO_PATH }}
    PR_NUMBER: ${{ inputs.PR_NUMBER }}
    VAULT_PURPOSE: ${{ inputs.VAULT_PURPOSE }}